### ISSUE TITLE
cannot update rule related to key 'common-c++:DuplicateBlocks'

### ISSUE THREAD

**Issue by Bertk** [jmecsoftware/QualityProfileEditorPlugin#6]
The update of the rule Fails with the error message:
![duplicateblocks-error](https://cloud.githubusercontent.com/assets/2315215/6430225/ef4ff4d4-c000-11e4-9a7f-eb8e6808e420.PNG)

**Comment by jmecosta** [comment]
will check...

**Comment by jmecosta** [comment]
this is now fixed.
